version: '3.7'
networks:
  net-transactions:

services:
  pulsar:
    image: "${PULSAR_IMAGE:-datastax/lunastreaming-all:2.10_0.2}"
    container_name: pulsar
    networks: [ "net-transactions" ]
    environment:
      - "PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
      - "transactionCoordinatorEnabled=true"
    ports:
      - '8080:8080'
      - '6650:6650'
    command: /bin/bash -c "/pulsar/bin/apply-config-from-env.py /pulsar/conf/standalone.conf && bin/pulsar standalone -nss"

